#!/usr/bin/env python3
"""
generate-dashboard.py — Render a Fivetran Ad Spend Analyzer HTML dashboard from JSON.

Usage:
  python3 generate-dashboard.py --data payload.json --output /tmp/dashboard.html
  echo '{...}' | python3 generate-dashboard.py --output /tmp/dashboard.html
  python3 generate-dashboard.py --help-schema

JSON Schema:
  {
    "title": "Cross-Channel Ad Performance",        # required
    "subtitle": "7 platforms · Apr 1 – May 1",     # optional
    "badge": "Data current as of May 1, 2026",     # optional — amber badge in header
    "kpis": [                                       # optional
      {
        "label": "Total Spend",
        "value": "$109.2K",
        "change": "+18.6%",
        "direction": "up",    # "up" (green), "down" (red), "neutral" (gray)
        "prior": "Prior: $92.0K"
      }
    ],
    "charts": [                                     # optional
      {
        "id": "chart1",          # unique DOM id — must match getElementById in script
        "title": "Spend by Platform",
        "layout": "half",        # "half" (2-col grid) or "full" (full-width), default "half"
        "height": 280,           # canvas height in px, default 280
        "script": "new Chart(document.getElementById('chart1'), { type: 'bar', data: { labels: ['Google Ads', 'Facebook Ads'], datasets: [{ label: 'Spend', data: [41507, 27117], backgroundColor: '#0073FF', borderRadius: 4 }] }, options: { plugins: { legend: { position: 'top' } }, scales: { x: { grid: { display: false } }, y: { ticks: { callback: v => '$' + (v/1000).toFixed(0) + 'K' } } } } });"
      }
    ],
    "anomalies": {                                  # optional
      "title": "Anomalies Detected",
      "items": ["Facebook ROAS fell -14.9% while spend rose +18.6%", "..."]
    },
    "table": {                                      # optional
      "title": "Campaign Performance",
      "columns": [
        {"key": "platform", "label": "Platform", "align": "left"},
        {"key": "spend", "label": "Spend", "align": "right"},
        {"key": "tier", "label": "Rating", "align": "left"}
      ],
      "rows": [
        {
          "platform": "Google Ads",
          "spend": "$12,981",
          "tier": {"html": "<span class='tier-badge tier-winner'>Winner</span>"}
        },
        {
          "platform": "Facebook Ads",
          "spend": "$5,423",
          "tier": {"html": "<span class='tier-badge tier-waste'>Waste</span>"},
          "_row_class": "highlight-waste"
        }
      ]
    },
    "custom_sections": [                            # optional — injected after table, before footer
      {"title": "Geographic Breakdown", "html": "<p>Any HTML here</p>"}
    ],
    "footer": "Generated by Fivetran Ad Spend Analyzer · May 1, 2026"
  }

charts[].script:
  Write the full `new Chart(...)` call as a JavaScript string. It is injected verbatim
  into the page's <script> block after fivetranColors and chartDefaults are defined, so
  you can reference those. Callbacks, dynamic colors, plugins, dual axes — all work
  because the script is real JS, not a JSON serialization of JS.

  Example with dual axes and axis formatters:
    "script": "new Chart(document.getElementById('chart3'), { type: 'bar', data: { labels: [...], datasets: [ { label: 'Spend', data: [...], backgroundColor: '#93C5FD', yAxisID: 'y' }, { label: 'ROAS', data: [...], type: 'line', borderColor: '#0073FF', yAxisID: 'y2' } ] }, options: { scales: { y: { position: 'left', ticks: { callback: v => '$' + (v/1000).toFixed(0) + 'K' } }, y2: { position: 'right', grid: { drawOnChartArea: false }, ticks: { callback: v => v + 'x' } } } } });"

table cell values:
  Plain string  → HTML-escaped (safe for user data)
  {"html": "…"} → injected as raw HTML (use for tier badges, links, formatted numbers)

Row classes for table._row_class:
  "highlight-winner"  — green tint row
  "highlight-waste"   — red tint row
  "highlight-caution" — yellow tint row
  (omit or empty string for default)

Escape hatch: if a dashboard requires a non-card/grid/table structure (multi-page layout,
non-Chart.js library, embedded tooling), read templates/dashboard.html directly and write
HTML manually instead of using this script. This should be rare.
"""

import argparse
import html
import json
import pathlib
import sys

SCRIPT_DIR = pathlib.Path(__file__).parent
DEFAULT_TEMPLATE = SCRIPT_DIR.parent / "templates" / "dashboard.html"
DEFAULT_OUTPUT = pathlib.Path("/tmp/dashboard.html")


def esc(text):
    return html.escape(str(text), quote=False)


def build_header(data):
    title = esc(data.get("title", "Ad Performance Dashboard"))
    subtitle = esc(data.get("subtitle", ""))
    badge = esc(data.get("badge", ""))
    badge_html = f'<span class="badge">{badge}</span>' if badge else ""
    subtitle_html = f"<p>{subtitle}</p>" if subtitle else ""
    return f"""<div class="header">
  <h1>{title}</h1>
  {subtitle_html}
  {badge_html}
</div>"""


def build_kpi_row(kpis):
    if not kpis:
        return ""
    cards = []
    for kpi in kpis:
        label = esc(kpi.get("label", ""))
        value = esc(kpi.get("value", ""))
        change = esc(kpi.get("change", ""))
        direction = kpi.get("direction", "neutral")
        prior = esc(kpi.get("prior", ""))
        change_class = {"up": "positive", "down": "negative"}.get(direction, "neutral")
        arrow = {"up": "&#9650;", "down": "&#9660;"}.get(direction, "")
        prior_html = f'<div class="prior">{prior}</div>' if prior else ""
        change_html = f'<div class="change {change_class}">{arrow} {change}</div>' if change else ""
        cards.append(f"""  <div class="kpi-card">
    <div class="label">{label}</div>
    <div class="value">{value}</div>
    {change_html}
    {prior_html}
  </div>""")
    return '<div class="kpi-row">\n' + "\n".join(cards) + "\n</div>"


def build_charts(charts):
    if not charts:
        return "", ""
    html_parts = []
    script_parts = []
    half_buffer = []

    def flush_half():
        if not half_buffer:
            return
        if len(half_buffer) == 1:
            html_parts.append(f'<div class="chart-grid">\n{half_buffer[0]}\n</div>')
        else:
            html_parts.append('<div class="chart-grid">\n' + "\n".join(half_buffer) + "\n</div>")
        half_buffer.clear()

    for chart in charts:
        cid = esc(chart.get("id", "chart"))
        title = esc(chart.get("title", ""))
        layout = chart.get("layout", "half")
        height = int(chart.get("height", 280))
        script = chart.get("script", "")

        if not script:
            print(f"Warning: chart '{cid}' has no 'script' field — canvas will be empty.", file=sys.stderr)

        card = f"""  <div class="chart-card">
    <h2>{title}</h2>
    <canvas id="{cid}" height="{height}" style="max-height:{height}px;"></canvas>
  </div>"""

        if layout == "full":
            flush_half()
            html_parts.append(f'<div class="chart-grid full">\n{card}\n</div>')
        else:
            half_buffer.append(card)
            if len(half_buffer) == 2:
                flush_half()

        if script:
            script_parts.append(script)

    flush_half()
    return "\n".join(html_parts), "\n".join(script_parts)


def build_anomalies(anomalies):
    if not anomalies:
        return ""
    title = esc(anomalies.get("title", "Anomalies Detected"))
    items = anomalies.get("items", [])
    if not items:
        return ""
    item_html = "\n".join(
        f'  <div class="anomaly-item"><div class="anomaly-dot"></div><div>{esc(item)}</div></div>'
        for item in items
    )
    return f"""<div class="anomaly-card">
  <h2>&#9888; {title}</h2>
{item_html}
</div>"""


def build_table(table):
    if not table:
        return ""
    title = esc(table.get("title", ""))
    columns = table.get("columns", [])
    rows = table.get("rows", [])
    if not columns:
        return ""

    header_cells = "".join(
        f'<th{"" if col.get("align", "left") == "left" else " class=\"number\""}>{esc(col.get("label", ""))}</th>'
        for col in columns
    )
    body_rows = []
    for row in rows:
        row_class = row.get("_row_class", "")
        style_map = {
            "highlight-waste": ' style="background:#FFF5F5;"',
            "highlight-winner": ' style="background:#F0FDF4;"',
            "highlight-caution": ' style="background:#FFFBEB;"',
        }
        row_style = style_map.get(row_class, "")
        cells = ""
        for col in columns:
            key = col.get("key", "")
            align_class = ' class="number"' if col.get("align") == "right" else ""
            val = row.get(key, "")
            if isinstance(val, dict) and "html" in val:
                cell_content = val["html"]
            else:
                cell_content = esc(str(val))
            cells += f"<td{align_class}>{cell_content}</td>"
        body_rows.append(f"      <tr{row_style}>{cells}</tr>")

    body_html = "\n".join(body_rows)
    return f"""<div class="table-card">
  <h2>{title}</h2>
  <table>
    <thead><tr>{header_cells}</tr></thead>
    <tbody>
{body_html}
    </tbody>
  </table>
</div>"""


def build_custom_sections(sections):
    if not sections:
        return ""
    parts = []
    for s in sections:
        title = esc(s.get("title", ""))
        inner = s.get("html", "")
        title_html = f"<h2>{title}</h2>" if title else ""
        parts.append(f'<div class="table-card">{title_html}{inner}</div>')
    return "\n".join(parts)


def build_footer(data):
    footer = esc(data.get("footer", "Generated by Fivetran Ad Spend Analyzer"))
    return f'<div class="footer">{footer}</div>'


def render(template_path, data):
    template = pathlib.Path(template_path).read_text(encoding="utf-8")

    header_html = build_header(data)
    kpi_html = build_kpi_row(data.get("kpis", []))
    chart_html, chart_scripts = build_charts(data.get("charts", []))
    anomaly_html = build_anomalies(data.get("anomalies"))
    table_html = build_table(data.get("table"))
    custom_html = build_custom_sections(data.get("custom_sections", []))
    footer_html = build_footer(data)

    body = "\n".join(filter(None, [
        header_html,
        kpi_html,
        chart_html,
        anomaly_html,
        table_html,
        custom_html,
        footer_html,
    ]))

    output = template
    output = output.replace("<!-- HEADER -->", header_html)
    output = output.replace("<!-- KPI_ROW -->", kpi_html)
    output = output.replace("<!-- CHART_GRID -->", chart_html)
    output = output.replace("<!-- ANOMALIES -->", anomaly_html)
    output = output.replace("<!-- TABLE -->", table_html)
    output = output.replace("<!-- CUSTOM_SECTIONS -->", custom_html)
    output = output.replace("<!-- FOOTER -->", footer_html)
    output = output.replace("<!-- BODY -->", body)
    output = output.replace("<!-- CHART_SCRIPTS -->", chart_scripts)

    title = data.get("title", "Ad Performance Dashboard")
    output = output.replace("{{TITLE}}", esc(title))

    return output


def main():
    parser = argparse.ArgumentParser(
        description="Render an ad-performance HTML dashboard from a JSON payload."
    )
    parser.add_argument("--data", help="Path to JSON payload file (default: read from stdin)")
    parser.add_argument(
        "--template",
        default=str(DEFAULT_TEMPLATE),
        help=f"Path to dashboard.html template (default: {DEFAULT_TEMPLATE})",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help=f"Output HTML path (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--help-schema",
        action="store_true",
        help="Print the JSON schema and exit",
    )
    args = parser.parse_args()

    if args.help_schema:
        print(__doc__)
        return

    if args.data:
        with open(args.data, encoding="utf-8") as f:
            data = json.load(f)
    else:
        raw = sys.stdin.read()
        if not raw.strip():
            print("Error: no JSON payload provided. Use --data or pipe JSON to stdin.", file=sys.stderr)
            sys.exit(1)
        data = json.loads(raw)

    html_out = render(args.template, data)
    out_path = pathlib.Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html_out, encoding="utf-8")
    print(out_path)


if __name__ == "__main__":
    main()
